-- 022_integration_catalog_seed.sql

insert into public.integration_catalog(code, name, category, description, plan_min, status, can_feed_knowledge, can_create_events, can_be_channel_provider, is_native_platform_service)
values
  ('whatsapp_business', 'WhatsApp Business', 'communication', 'Integração de comunicação para canais de atendimento via WhatsApp.', 'student', 'available', false, false, true, false),
  ('email', 'E-mail', 'communication', 'Caixas e threads para atendimento e registro.', 'student', 'available', true, true, true, false),
  ('discord', 'Discord', 'communication', 'Comunidades, canais técnicos e operação de times.', 'pro', 'available', true, true, true, false),
  ('telegram', 'Telegram', 'communication', 'Mensageria instantânea para atendimento e comunidades.', 'pro', 'available', false, true, true, false),
  ('teams', 'Microsoft Teams', 'communication', 'Mensagens corporativas, times e canais internos.', 'pro', 'available', true, true, true, false),
  ('instagram', 'Instagram', 'social', 'Rede social do ecossistema Meta.', 'pro', 'planned', true, false, true, false),
  ('x_twitter', 'X / Twitter', 'social', 'Monitoramento e interação em publicações autorizadas.', 'pro', 'planned', true, false, false, false),
  ('threads', 'Threads', 'social', 'Rede social de conversas públicas do ecossistema Meta.', 'pro', 'planned', true, false, false, false),
  ('google_drive', 'Google Drive', 'knowledge', 'Pastas e arquivos para base de conhecimento.', 'student', 'available', true, false, false, false),
  ('sharepoint', 'SharePoint', 'knowledge', 'Sites, bibliotecas e documentos corporativos.', 'pro', 'available', true, false, false, false),
  ('notion', 'Notion', 'knowledge', 'Páginas, bases e documentação de trabalho.', 'pro', 'available', true, true, false, false),
  ('jira', 'Jira', 'atlassian-dev', 'Issues, projetos, backlog e tarefas.', 'pro', 'available', true, true, false, false),
  ('jira_service_management', 'Jira Service Management', 'support-service-desk', 'Portal, filas, tickets e service desk Atlassian.', 'pro', 'available', true, true, true, false),
  ('confluence', 'Confluence', 'atlassian-dev', 'Espaços e páginas de documentação.', 'pro', 'available', true, false, false, false),
  ('trello', 'Trello', 'atlassian-dev', 'Quadros, listas e cartões.', 'student', 'available', false, true, false, false),
  ('bitbucket', 'Bitbucket', 'atlassian-dev', 'Repositórios e versionamento Atlassian.', 'pro', 'planned', true, true, false, false),
  ('github', 'GitHub', 'atlassian-dev', 'Repositórios, issues e pull requests.', 'pro', 'available', true, true, false, false),
  ('monday', 'monday.com', 'work-management', 'Quadros, automações e gestão operacional.', 'pro', 'available', false, true, false, false),
  ('asana', 'Asana', 'work-management', 'Projetos, tarefas e equipes.', 'pro', 'planned', false, true, false, false),
  ('clickup', 'ClickUp', 'work-management', 'Tarefas, documentos e gestão de trabalho.', 'pro', 'planned', false, true, false, false),
  ('salesforce', 'Salesforce', 'crm-marketing', 'CRM, contas, oportunidades e pipeline.', 'pro', 'available', false, true, false, false),
  ('hubspot', 'HubSpot', 'crm-marketing', 'CRM, marketing, vendas e atendimento.', 'pro', 'available', false, true, false, false),
  ('pipedrive', 'Pipedrive', 'crm-marketing', 'Funil comercial e atividades de venda.', 'pro', 'planned', false, true, false, false),
  ('bling', 'Bling', 'erp-commerce-finance', 'Produtos, pedidos, estoque, notas e operação comercial.', 'pro', 'available', false, true, false, false),
  ('tiny_erp', 'Tiny ERP', 'erp-commerce-finance', 'ERP, pedidos, produtos, estoque e e-commerce.', 'pro', 'planned', false, true, false, false),
  ('omie', 'Omie', 'erp-commerce-finance', 'ERP, financeiro, vendas e serviços.', 'pro', 'planned', false, true, false, false),
  ('zendesk', 'Zendesk', 'support-service-desk', 'Tickets, central de ajuda e suporte.', 'pro', 'available', true, true, true, false),
  ('freshdesk', 'Freshdesk', 'support-service-desk', 'Tickets, suporte e base de conhecimento.', 'pro', 'planned', true, true, true, false),
  ('custom_rest_api', 'API REST personalizada', 'custom-api', 'Conector guiado para APIs REST específicas do cliente.', 'pro', 'available', true, true, false, false),
  ('custom_graphql_api', 'API GraphQL personalizada', 'custom-api', 'Conector guiado para APIs GraphQL específicas do cliente.', 'pro', 'planned', false, true, false, false),
  ('incoming_webhook', 'Webhook de entrada', 'custom-api', 'Recebe eventos externos para gerar atendimento, alerta ou tarefa.', 'pro', 'available', false, true, false, false),
  ('outgoing_webhook', 'Webhook de saída', 'custom-api', 'Envia eventos do produto para sistemas externos.', 'pro', 'available', false, true, false, false),
  ('openai', 'OpenAI', 'ai-voice', 'Modelos de IA, geração, análise e embeddings.', 'pro', 'available', false, false, false, false),
  ('transcription', 'Transcrição de áudio', 'ai-voice', 'Transcrição de áudios para atendimento, conhecimento e auditoria.', 'pro', 'planned', true, false, false, false),
  ('ocr', 'OCR', 'ai-voice', 'Extração de texto em imagens e documentos digitalizados.', 'pro', 'planned', true, false, false, false),
  ('correios_cep', 'Correios / CEP', 'native-platform-service', 'Serviço nativo de CEP controlado pela plataforma.', 'basic', 'native', false, false, false, true),
  ('maps_geolocation', 'Maps / geolocalização / rotas', 'native-platform-service', 'Serviço nativo de mapa e geolocalização controlado pela plataforma.', 'basic', 'native', false, false, false, true)
on conflict (code) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  plan_min = excluded.plan_min,
  status = excluded.status,
  can_feed_knowledge = excluded.can_feed_knowledge,
  can_create_events = excluded.can_create_events,
  can_be_channel_provider = excluded.can_be_channel_provider,
  is_native_platform_service = excluded.is_native_platform_service;
